3-Semester-Organisation/DivEx-Frontend

- package-lock.json
- package.json
- src/App.jsx
- src/components/ui/custom/NavBar.tsx
- src/js/jwt.ts
- src/js/util.js
- src/views/portfolioOverview.tsx
also util for decoding jwt in frontend, probably useful later
using zod for form control
probably need more security
brain is cooked tho
> added button and method for creating portfolio

- src/views/stockDetailsPage.tsx
enabled page saving for stockDetailsPage, now it fetches the stock data instead of relying on object transfer from previous page. Switched from using useLocation() to useEffect() and useState()
> Enabeld page saving

- src/views/stockDetailsPage.tsx
Yeah, removed stock from dependcy list of useEffect, so as not to endless selfTrigger and loop.
> Fixed Chris Big Mistake, Endless loop on StockDetailsPage

- src/js/AuthContext.tsx
- src/js/jwt.ts
- src/views/portfolioOverview.tsx
added method in jwt.ts to get subtype from token
added state in authcontext for subtype, and method to update it
added testing div to portfolioOverview to see current subtype
> added subtype to authcontext

- src/components/ui/custom/createPortfolioButton.tsx
- src/js/AuthContext.tsx
- src/js/util.js
- src/views/portfolioOverview.tsx
added function to limit portfolios for free and premium users
a toast will pop up when you try to click create portfolio button
> added limit for portfolios

- src/components/divex/DividendInfo.tsx
- src/components/divex/HistoricalDividendChart.tsx
- src/components/divex/StockGraph.tsx
- src/views/stockDetailsPage.tsx
- src/views/stocksPage.tsx
fixed time frame selector, by using empty dependency array for the useEffect
> Fixed Price movement chart and Dark/lightmode

- src/components/ui/custom/createPortfolioButton.tsx
- src/components/ui/custom/portfolioEditDialog.tsx
- src/components/ui/input.tsx
- src/views/calendarPage.tsx
- src/views/homepage.tsx
- src/views/login.tsx
- src/views/portfolioOverview.tsx
- src/views/register.tsx
- src/views/stockDetailsPage.tsx
- src/views/stocksPage.tsx
changed all static color classes to responsive light/dark
formatted some components for better styling
added "go back" button to stock details view
added consistent size and style for headers
> Colorscheme

- package-lock.json
- package.json
- pnpm-lock.yaml
- src/components/ui/custom/DividendCalendar.tsx
- src/components/ui/custom/DividendTable.tsx
- src/components/ui/custom/createPortfolioButton.tsx
- src/components/ui/custom/portfolioEditDialog.tsx
- src/components/ui/custom/stockTable.tsx
- src/components/ui/input.tsx
- src/components/ui/tooltip.tsx
- src/views/calendarPage.tsx
- src/views/homepage.tsx
- src/views/login.tsx
- src/views/portfolioOverview.tsx
- src/views/register.tsx
- src/views/stockDetailsPage.tsx
- src/views/stocksPage.tsx
all dividend dates show up in calendar
when clicking a date with dividend, fetches table containing all stocks that pay out that day
when clicking reset, fetches table containing all stocks
unix and dates can SUCK my fuckin DICK holy shit
> Calendar update 2

- src/App.jsx
- src/api/portfolio.ts
- src/api/stocks.ts
- src/components/divex/AddStockModal.tsx
- src/components/divex/DividendInfo.tsx
- src/components/divex/HistoricalDividendChart.tsx
- src/components/divex/PortfolioTable.tsx
- src/components/divex/StockGraph.tsx
- src/components/divex/searchBar.tsx
- src/components/ui/custom/createPortfolioButton.tsx
- src/components/ui/custom/portfolioEditDialog.tsx
- src/components/ui/custom/portfolioSelect.tsx
- src/divextypes/types.ts
- src/js/PortfoliosContext.tsx
- src/js/util.ts
- src/views/homepage.tsx
- src/views/portfolioOverview.tsx
- src/views/stockDetailsPage.tsx
- src/views/stocksPage.tsx
**Nuværende mangler**
mangler at implementerer addStockModal to stocksPage.tsx)
**Bugs :D**
når man laver en ny portfolio og vælger får man white screen, reload af siden fixer det
**--------------------------------------------------------------------------------------------------------------------------------------------**
created global types for; portfolio, stock, paginated response, historicalprincing... majority of backend models
created searhbar component
- can search by ticker or stock name
- displays no results if it cant find anything
created addStockModal Component
- can select portfolio to add stock to
- form validation
- add btn to stocksDetailsPage
Created portfolio table component
created currency selection (only supports DKK, SEK, NOK)
- added percentage change
> Portfolio overview

- src/js/useCredentials.tsx
bug:  if logged in and on the portfolio overview page, when refreshed youll be redirected to login.
fix: changed check on token instead of isLoggedIn state
> Bugfix (useCheckCredentials)

- src/components/ui/custom/pie-chart.tsx
- src/views/portfolioOverview.tsx
updated again, should work properly now
chart shows up on both dividend and stock view
added shadcn styling to buttons and dropdown
aligned searchbar with other buttons
removed bunch of unnecessary flex stylings, merged into one instead
> updated portfolio style

- src/components/divex/AddStockModal.tsx
- src/components/ui/custom/add-stock-dialog.tsx
- src/components/ui/custom/portfolioEditDialog.tsx
- src/views/stockDetailsPage.tsx
used zod to handle form validation
> Add stock dialog update

- src/components/divex/DividendSummaryTable.tsx
- src/components/divex/PortfolioTable.tsx
- src/views/portfolioOverview.tsx
- Lifted numberFormmater function into portfolio overview.
- Changed formating for DividendSummaryTable component
> European number formating

- src/components/divex/PortfolioTable.tsx
- src/components/ui/custom/pie-chart.tsx
- src/views/portfolioOverview.tsx
- refactored some code, and extracted some logic into seperate reuseable functions
- added switch containing sort logic
- made column headers clickable, enabeling sorting
> Sort Portfolio Table 

- src/components/divex/DividendSummaryTable.tsx
- src/components/divex/PortfolioTable.tsx
- src/js/util.ts
- src/views/portfolioOverview.tsx
- added comparison for market value based on base currency and a selected currency
- added comparioson for annual dividends
> Side by side comparison

- src/views/portfolioOverview.tsx
changed icon to use lucide instead of react-icons
changed toast style to info
changed toast message to be "professional"
> changes to share button

- src/components/divex/PortfolioTable.tsx
- src/components/ui/custom/stockTable.tsx
- src/index.css
- src/views/portfolioOverview.tsx
- src/views/stocksPage.tsx
capitalized table heads
changed stocksPage to use stocksTable component
added simulated network delay to show off slick skeleton loading animation
spanned portfolio table to whole page
> normalized all tables

- src/components/ui/custom/add-stock-dialog.tsx
- src/components/ui/custom/stockTable.tsx
added "Add" button to main stocksTable
> Add button to table

- src/api/user.ts
- src/components/ui/custom/settings-form.tsx
- src/views/settings.tsx
added settings page
can change user details, and password separately
can edit individual values separately, all fields except email is optional
can't delete values again after setting them, might look into it later idk
zod for form control
> Settings page

- src/components/divex/DividendBarChart.tsx
- src/components/divex/DividendSummaryTable.tsx
- src/components/divex/MonthSelector.tsx
- src/components/divex/PortfolioTable.tsx
- src/components/divex/searchBar.tsx
- src/components/ui/custom/pie-chart.tsx
- src/views/portfolioOverview.tsx
current styling issues:
- the chart is very rigid not flexiable at all
- also the height does not align with the piechart
- when hovering over a bar the background turns white
- the top of the bars that has a high value gets cutted off
--------------------------------------------------------------------------------------------------------------------------------------------
created component DividendBarChart
created function to aproximate the frequency a stock payouts dividends.
created component MonthSelector
conditionally render the barchart along with month selector when showing dividends.
bar chart also shows total expected dividend for a selected month.
made it possible to convert the dividens to a selected currency
> Monthly dividend breakdown

- src/App.jsx
- src/components/ui/custom/NavBar.tsx
- src/views/trendingPage.tsx
changed "homepage" to "trending"
removed dashboard from router and navbar
> updated routing

- index.html
- src/components/divex/searchBar.tsx
- src/views/portfolioOverview.tsx
- src/views/stocksPage.tsx
> added better searchbar to stockspage

- src/api/portfolio.ts
- src/components/divex/DividendBarChart.tsx
- src/components/divex/PortfolioTable.tsx
- src/components/ui/custom/add-stock-dialog.tsx
- src/divextypes/types.ts
- src/js/PortfoliosContext.tsx
- src/views/portfolioOverview.tsx
- added function for summarizing multiple same entries
- added new state = summarizedPortfolios, passed this down to children components instead of selecedPortfolio.
- added useEffect that updates summarizedPortfolios on stateChange for SelectedPortfolio.
- added coloum P/L to portfolioTable.
- added function for calculating P/L in PortfolioTable
- Cleaned up code, removed console.log(), unused code and commented out code
> (FIX) Add Multiple same entries

- src/js/PortfoliosContext.tsx
- src/views/portfolioOverview.tsx
changed fetchAndSetPortfolios, was assigning selectedPortfolio incorrectly
added if statement to check for portfolio before iterating
> small bug fix

- .env.development
- .env.production
- index.html
- package-lock.json
- package.json
- src/App.jsx
- src/api/portfolio.ts
- src/api/stocks.ts
- src/api/subscription.ts
- src/api/user.ts
- tsconfig.json
- vite-env.d.ts
- vite.config.js
created .env.production and .env.development 
populted the files with values for url
importent env url values and made use of the these in fetch calls in api folder
> .env files

- src/views/trendingPage.tsx
added 2 hardcoded arrays
commented out the other code
> Trending stocks test data

- src/App.jsx
- src/api/portfolio.ts
- src/components/divex/searchBar.tsx
- src/components/ui/custom/NavBar.tsx
- src/components/ui/custom/defaultNavbar.tsx
- src/views/calendarPage.tsx
- src/views/portfolioOverview.tsx
- src/views/stockDetailsPage.tsx
- src/views/stocksPage.tsx
added searchbar to navbar and default navbar
moved theme changer down a level to match profile and upgrade button
changed home thingy to a burgermenu icon
> small-ui-changes

- src/js/AuthContext.tsx
> fixed subtype on login/logout

- src/api/portfolio.ts
- src/components/ui/custom/add-stock-dialog.tsx
enforced rule for limiting number of stocks that can be added to a portfolio for a free user, by setting state after adding a stock
> Fixed enforcement rule
